import type { PortfolioItem } from '@/types'

export const portfolioItems: PortfolioItem[] = [
  {
    id: 'port-001',
    title: 'Royal Rajputana Wedding',
    category: 'wedding',
    coverImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=80',
    ],
    date: '2024-11-15',
    location: 'Udaipur, Rajasthan',
    description: 'A 4-day royal wedding celebration with 600 guests at a heritage palace property. Featuring a grand mehendi, sangeet with celebrity performers, and a reception with elaborate floral installations.',
    tags: ['Heritage Venue', 'Destination Wedding', 'Celebrity Performance', '600+ Guests'],
    featured: true,
  },
  {
    id: 'port-002',
    title: 'Tech Summit 2024',
    category: 'corporate',
    coverImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
    date: '2024-10-08',
    location: 'Bangalore, Karnataka',
    description: 'Annual technology conference for India\'s leading IT company. 1200 delegates, 40+ speakers, 3-day event with workshops, keynotes, and a gala dinner.',
    tags: ['1200 Delegates', 'Multi-day', 'Gala Dinner', 'Live Streaming'],
    featured: true,
  },
  {
    id: 'port-003',
    title: 'Patel-Sharma Destination Wedding',
    category: 'wedding',
    coverImage: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&q=80',
    date: '2025-02-20',
    location: 'Goa',
    description: 'A breathtaking beachside destination wedding for 250 guests. Sunset ceremony on the beach, tropical-themed mehendi, and a rooftop reception under the stars.',
    tags: ['Beachside', 'Tropical Theme', 'Sunset Ceremony', '250 Guests'],
    featured: true,
  },
  {
    id: 'port-004',
    title: 'Aurora Luxury Birthday Gala',
    category: 'social',
    coverImage: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80',
    date: '2024-09-12',
    location: 'Mumbai, Maharashtra',
    description: 'A spectacular 40th birthday celebration with aurora borealis theme. Custom LED installations, live jazz band, and personalized floral arrangements for 150 guests.',
    tags: ['Custom Theme', 'LED Installation', 'Live Band', '150 Guests'],
    featured: false,
  },
  {
    id: 'port-005',
    title: 'Pioneer Auto Product Launch',
    category: 'corporate',
    coverImage: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80',
    date: '2024-12-05',
    location: 'Delhi',
    description: 'High-impact product launch event for a leading automotive brand. Dramatic reveal with smoke effects, LED wall presentations, press conference setup, and influencer coordination.',
    tags: ['Product Reveal', 'Press Conference', 'LED Walls', 'Influencer Event'],
    featured: true,
  },
  {
    id: 'port-006',
    title: 'Golden Anniversary Surprise',
    category: 'social',
    coverImage: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&q=80',
    date: '2025-03-14',
    location: 'Jaipur, Maharashtra',
    description: 'A beautifully orchestrated 50th anniversary surprise celebration. Family coordination across 3 cities, vintage theme décor, photo journey installation, and live acoustic performances.',
    tags: ['Anniversary', 'Surprise Event', 'Vintage Theme', 'Family Event'],
    featured: false,
  },
  {
    id: 'port-007',
    title: 'Heritage Sangeet Night',
    category: 'wedding',
    coverImage: 'https://images.unsplash.com/photo-1611338946659-c98ba2e2e49b?w=800&q=80',
    date: '2025-01-10',
    location: 'Jaipur, Rajasthan',
    description: 'An extraordinary sangeet night combining Rajasthani folk performances with Bollywood entertainment. Custom stage with marigold backdrop, professional DJ, and fireworks finale.',
    tags: ['Sangeet', 'Folk Performance', 'Rajasthani Theme', 'Fireworks'],
    featured: false,
  },
  {
    id: 'port-008',
    title: 'Sunrise Group Dealer Meet',
    category: 'corporate',
    coverImage: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&q=80',
    date: '2024-08-22',
    location: 'Hyderabad, Telangana',
    description: 'Annual dealer meet for 800 dealers from across India. 2-day event featuring product presentations, recognition awards, networking dinner, and entertainment show.',
    tags: ['800+ Delegates', 'Awards', 'Networking', '2-Day Event'],
    featured: false,
  },
]

export const getFeaturedPortfolio = () => portfolioItems.filter((p) => p.featured)

export const getPortfolioByCategory = (category: PortfolioItem['category']) =>
  portfolioItems.filter((p) => p.category === category)
