import type { Service, ServiceCategoryConfig } from '@/types'

export const serviceCategories: ServiceCategoryConfig[] = [
  {
    id: 'wedding',
    label: 'Wedding Events',
    href: '/services/wedding-events',
    icon: '💍',
    shortDesc: 'From intimate ceremonies to grand celebrations — every detail perfected.',
    items: [
      { label: 'Wedding Planning', href: '/services/wedding-events#planning' },
      { label: 'Destination Weddings', href: '/services/wedding-events#destination' },
      { label: 'Haldi Ceremony', href: '/services/wedding-events#haldi' },
      { label: 'Mehendi Night', href: '/services/wedding-events#mehendi' },
      { label: 'Sangeet Event', href: '/services/wedding-events#sangeet' },
      { label: 'Reception', href: '/services/wedding-events#reception' },
      { label: 'Guest Management', href: '/services/wedding-events#guests' },
      { label: 'Wedding Décor', href: '/services/wedding-events#decor' },
    ],
  },
  {
    id: 'corporate',
    label: 'Corporate Events',
    href: '/services/corporate-events',
    icon: '🏢',
    shortDesc: 'Professional events that elevate your brand and inspire your team.',
    items: [
      { label: 'Conferences', href: '/services/corporate-events#conferences' },
      { label: 'Product Launches', href: '/services/corporate-events#launches' },
      { label: 'Award Functions', href: '/services/corporate-events#awards' },
      { label: 'Dealer Meets', href: '/services/corporate-events#dealer-meets' },
      { label: 'Annual Meetings', href: '/services/corporate-events#meetings' },
      { label: 'Team Building Events', href: '/services/corporate-events#team-building' },
    ],
  },
  {
    id: 'social',
    label: 'Social Events',
    href: '/services/social-events',
    icon: '🎉',
    shortDesc: 'Celebrate life\'s precious moments with style and sophistication.',
    items: [
      { label: 'Birthday Parties', href: '/services/social-events#birthday' },
      { label: 'Anniversary Celebrations', href: '/services/social-events#anniversary' },
      { label: 'Cultural Programs', href: '/services/social-events#cultural' },
      { label: 'Family Events', href: '/services/social-events#family' },
    ],
  },
  {
    id: 'entertainment',
    label: 'Entertainment Services',
    href: '/services/entertainment-services',
    icon: '🎤',
    shortDesc: 'World-class entertainment that transforms events into unforgettable experiences.',
    items: [
      { label: 'Professional Anchors', href: '/services/entertainment-services#anchors' },
      { label: 'DJ Services', href: '/services/entertainment-services#dj' },
      { label: 'Live Bands', href: '/services/entertainment-services#bands' },
      { label: 'Celebrity Management', href: '/services/entertainment-services#celebrity' },
      { label: 'Artist Booking', href: '/services/entertainment-services#artists' },
    ],
  },
  {
    id: 'production',
    label: 'Production Setup',
    href: '/services/production-setup',
    icon: '🎬',
    shortDesc: 'Cutting-edge production and AV technology for flawless event execution.',
    items: [
      { label: 'Stage Design', href: '/services/production-setup#stage' },
      { label: 'LED Walls', href: '/services/production-setup#led' },
      { label: 'Sound Systems', href: '/services/production-setup#sound' },
      { label: 'Lighting Setup', href: '/services/production-setup#lighting' },
      { label: 'Photography', href: '/services/production-setup#photography' },
      { label: 'Videography', href: '/services/production-setup#videography' },
      { label: 'Drone Coverage', href: '/services/production-setup#drone' },
    ],
  },
]

export const services: Service[] = [
  {
    id: 'wedding-planning',
    slug: 'wedding-planning',
    name: 'Wedding Planning',
    category: 'wedding',
    description: 'Complete end-to-end wedding planning from venue selection to final execution. We handle every detail so you can focus on cherishing every moment.',
    shortDesc: 'End-to-end wedding planning with impeccable attention to detail.',
    icon: '💍',
    image: '/images/services/wedding-planning.jpg',
    subServices: ['Venue Selection', 'Vendor Management', 'Timeline Planning', 'Budget Management', 'Day-of Coordination'],
    featured: true,
    order: 1,
  },
  {
    id: 'destination-wedding',
    slug: 'destination-wedding',
    name: 'Destination Weddings',
    category: 'wedding',
    description: 'Your dream wedding in the world\'s most breathtaking locations. From Udaipur palaces to Goa beaches, we make destination weddings seamless.',
    shortDesc: 'Dream weddings at iconic destinations across India and abroad.',
    icon: '✈️',
    image: '/images/services/destination-wedding.jpg',
    subServices: ['Location Scouting', 'Travel Coordination', 'Guest Logistics', 'Local Vendor Management', 'Accommodation'],
    featured: true,
    order: 2,
  },
  {
    id: 'corporate-conferences',
    slug: 'corporate-conferences',
    name: 'Conferences',
    category: 'corporate',
    description: 'Large-scale corporate conferences with professional AV setup, speaker management, and seamless attendee experience.',
    shortDesc: 'Professional conferences that impress delegates and drive impact.',
    icon: '🎙️',
    image: '/images/services/conference.jpg',
    subServices: ['AV Setup', 'Speaker Management', 'Registration Desk', 'Branding', 'Live Streaming'],
    featured: true,
    order: 1,
  },
  {
    id: 'product-launch',
    slug: 'product-launch',
    name: 'Product Launches',
    category: 'corporate',
    description: 'Make your product launch a media event. Dramatic reveals, press coverage, and brand experiences that generate buzz.',
    shortDesc: 'High-impact product launches that create lasting brand moments.',
    icon: '🚀',
    image: '/images/services/product-launch.jpg',
    subServices: ['Concept Design', 'Stage Setup', 'Media Management', 'Influencer Coordination', 'Live Coverage'],
    featured: false,
    order: 2,
  },
  {
    id: 'social-birthday',
    slug: 'birthday-parties',
    name: 'Birthday Parties',
    category: 'social',
    description: 'Milestone birthday celebrations tailored to your vision — from intimate gatherings to grand birthday galas.',
    shortDesc: 'Unforgettable birthday celebrations for all ages and milestones.',
    icon: '🎂',
    image: '/images/services/birthday.jpg',
    subServices: ['Theme Design', 'Decoration', 'Entertainment', 'Catering Coordination', 'Photography'],
    featured: false,
    order: 1,
  },
  {
    id: 'entertainment-dj',
    slug: 'dj-services',
    name: 'DJ Services',
    category: 'entertainment',
    description: 'Professional DJ services with premium sound systems. From Bollywood to EDM, we set the perfect mood for every moment.',
    shortDesc: 'Premium DJ services that keep the energy alive all night.',
    icon: '🎵',
    image: '/images/services/dj.jpg',
    subServices: ['DJ Performance', 'Sound System', 'Lighting', 'Song Requests', 'MC Services'],
    featured: false,
    order: 2,
  },
  {
    id: 'production-stage',
    slug: 'stage-design',
    name: 'Stage Design',
    category: 'production',
    description: 'Stunning stage designs that create the perfect backdrop for your event. From grand mandaps to corporate stages.',
    shortDesc: 'Spectacular stage designs that command attention and inspire awe.',
    icon: '🎭',
    image: '/images/services/stage.jpg',
    subServices: ['Concept Design', 'Fabrication', 'Setup & Dismantling', '3D Visualization', 'Custom Branding'],
    featured: false,
    order: 1,
  },
]
