import type { Service, ServiceCategoryConfig } from '@/types'

export const serviceCategories: ServiceCategoryConfig[] = [
  {
    id: 'wedding',
    label: 'Wedding & Sangeet Anchoring',
    href: '/services/wedding-events',
    icon: '💍',
    shortDesc: 'Ceremony, sangeet and reception hosting — with live singing and crowd games built in.',
    items: [
      { label: 'Wedding Ceremony Hosting', href: '/services/wedding-events#ceremony' },
      { label: 'Sangeet Night Anchoring', href: '/services/wedding-events#sangeet' },
      { label: 'Cocktail & Reception Hosting', href: '/services/wedding-events#reception' },
      { label: 'Varmala / Jaimala Compering', href: '/services/wedding-events#varmala' },
      { label: 'Haldi & Mehendi Hosting', href: '/services/wedding-events#haldi' },
      { label: 'Live Singing Sets', href: '/services/wedding-events#singing' },
      { label: 'Interactive Crowd Games', href: '/services/wedding-events#games' },
      { label: 'Custom Script & Run-of-Show', href: '/services/wedding-events#script' },
    ],
  },
  {
    id: 'corporate',
    label: 'Corporate Hosting & Emceeing',
    href: '/services/corporate-events',
    icon: '🎤',
    shortDesc: 'A polished, bilingual host who keeps your agenda sharp and your audience engaged.',
    items: [
      { label: 'Conferences & Summits', href: '/services/corporate-events#conferences' },
      { label: 'Award Nights', href: '/services/corporate-events#awards' },
      { label: 'Product Launches', href: '/services/corporate-events#launches' },
      { label: 'Annual Days', href: '/services/corporate-events#annual' },
      { label: 'Dealer Meets', href: '/services/corporate-events#dealer-meets' },
    ],
  },
  {
    id: 'social',
    label: 'Private & Celebrity Events',
    href: '/services/social-events',
    icon: '🎉',
    shortDesc: 'Birthdays, anniversaries, celebrity nights and cultural shows hosted with warmth and wit.',
    items: [
      { label: 'Birthday Parties', href: '/services/social-events#birthday' },
      { label: 'Anniversaries', href: '/services/social-events#anniversary' },
      { label: 'Celebrity Nights', href: '/services/social-events#celebrity' },
      { label: 'College Festivals', href: '/services/social-events#college' },
    ],
  },
  {
    id: 'entertainment',
    label: 'Live Entertainment & Singing',
    href: '/services/entertainment-services',
    icon: '🎶',
    shortDesc: 'The front-man for your event — live singing, games and non-stop audience energy.',
    items: [
      { label: 'Live Singing', href: '/services/entertainment-services#singing' },
      { label: 'Interactive Crowd Games', href: '/services/entertainment-services#games' },
      { label: 'Audience Engagement', href: '/services/entertainment-services#engagement' },
      { label: 'Band & DJ Coordination', href: '/services/entertainment-services#coordination' },
    ],
  },
  {
    id: 'production',
    label: 'Show Design & Scripting',
    href: '/services/production-setup',
    icon: '📝',
    shortDesc: 'A custom script and run-of-show so your event flows without a dull moment.',
    items: [
      { label: 'Custom Event Scripts', href: '/services/production-setup#scripts' },
      { label: 'Run-of-Show Design', href: '/services/production-setup#flow' },
      { label: 'Rehearsals & Cues', href: '/services/production-setup#rehearsal' },
      { label: 'On-Stage Coordination', href: '/services/production-setup#coordination' },
    ],
  },
]

export const services: Service[] = [
  {
    id: 'sangeet-anchoring',
    slug: 'sangeet-anchoring',
    name: 'Sangeet Night Anchoring',
    category: 'wedding',
    description: 'High-energy sangeet hosting with scripted family face-offs, crowd games and live singing that keeps every generation on the dance floor.',
    shortDesc: 'High-energy sangeet hosting that keeps the whole family dancing.',
    icon: '🎶',
    image: '/images/sangeet.jpeg',
    subServices: ['Custom Script', 'Family Games', 'Live Singing', 'Choreo Cues', 'Crowd Interaction'],
    featured: true,
    order: 1,
  },
  {
    id: 'wedding-hosting',
    slug: 'wedding-hosting',
    name: 'Wedding & Reception Hosting',
    category: 'wedding',
    description: 'Warm, perfectly paced hosting across every function — varmala, cocktail and reception — in Hindi, English and Rajasthani.',
    shortDesc: 'Warm, perfectly paced hosting for every wedding function.',
    icon: '💍',
    image: '/images/wedding.jpeg',
    subServices: ['Varmala Compering', 'Reception Hosting', 'Bilingual', 'Run-of-Show', 'Guest Engagement'],
    featured: true,
    order: 2,
  },
  {
    id: 'corporate-emcee',
    slug: 'corporate-emcee',
    name: 'Corporate Emceeing',
    category: 'corporate',
    description: 'Professional emceeing for conferences, award nights and launches — tight on time, sharp on transitions, engaging from start to finish.',
    shortDesc: 'Polished corporate hosting that keeps delegates engaged.',
    icon: '🎤',
    image: '/images/corparate.jpeg',
    subServices: ['Agenda Flow', 'Bilingual Hosting', 'Award Segments', 'Q&A Moderation', 'Brand Tone'],
    featured: true,
    order: 1,
  },
  {
    id: 'award-nights',
    slug: 'award-nights',
    name: 'Award Nights & Launches',
    category: 'corporate',
    description: 'Build anticipation, make leadership shine and land clean applause moments with a host who owns the stage and the countdown.',
    shortDesc: 'High-impact hosting for launches and award ceremonies.',
    icon: '🏆',
    image: '/images/entertainment.jpeg',
    subServices: ['Scripted Reveal', 'Recognition Segments', 'Press Moments', 'Energy Management'],
    featured: false,
    order: 2,
  },
  {
    id: 'private-events',
    slug: 'private-events',
    name: 'Birthdays & Private Events',
    category: 'social',
    description: 'Intimate celebrations hosted like a show — themed games, roasts, and surprise live singing sets tailored to the guest of honour.',
    shortDesc: 'Private celebrations hosted with energy and a personal touch.',
    icon: '🎂',
    image: '/images/birthday.jpeg',
    subServices: ['Themed Games', 'Live Singing', 'Personal Roasts', 'Surprise Cues', 'Crowd Fun'],
    featured: false,
    order: 1,
  },
  {
    id: 'live-singing',
    slug: 'live-singing',
    name: 'Live Singing & Entertainment',
    category: 'entertainment',
    description: 'A host who can also sing. When the moment deserves goosebumps, Shubham puts down the script and delivers a live performance.',
    shortDesc: 'Live singing sets and interactive entertainment on demand.',
    icon: '🎵',
    image: '/images/entertainment.jpeg',
    subServices: ['Live Vocals', 'Audience Games', 'Band Coordination', 'Song Dedications', 'Energy Sets'],
    featured: false,
    order: 2,
  },
  {
    id: 'show-scripting',
    slug: 'show-scripting',
    name: 'Show Design & Scripting',
    category: 'production',
    description: 'A bespoke script and run-of-show built around your people and timeline — rehearsed, cued and coordinated so nothing feels off.',
    shortDesc: 'Custom scripts and run-of-show design for a seamless event.',
    icon: '📝',
    image: '/images/setup.jpeg',
    subServices: ['Custom Script', 'Run-of-Show', 'Rehearsals', 'Cue Sheets', 'On-Stage Coordination'],
    featured: false,
    order: 1,
  },
]
