import type { Testimonial } from '@/types'

export const testimonials: Testimonial[] = [
  {
    id: 'test-001',
    name: 'Priya & Arjun Sharma',
    role: 'Wedding Clients',
    location: 'Mumbai',
    eventType: 'wedding',
    rating: 5,
    quote: "Anchor Shubham Khandelwal  turned our wedding into an absolute fairy tale. Every single detail — from the floral arrangements to the lighting — was executed with such precision. Our guests are still talking about it months later. Truly the best decision we ever made.",
    date: '2024-11-15',
    platform: 'google',
    featured: true,
  },
  {
    id: 'test-002',
    name: 'Rajesh Mehta',
    role: 'CEO, Mehta Industries',
    location: 'Delhi',
    eventType: 'corporate',
    rating: 5,
    quote: "Our annual conference hosted by Anchor Shubham Khandelwal  was nothing short of spectacular. The production quality, AV setup, and seamless management exceeded our expectations. We'll be working with them exclusively for all future corporate events.",
    date: '2024-10-08',
    platform: 'google',
    featured: true,
  },
  {
    id: 'test-003',
    name: 'Kavita & Sanjay Patel',
    role: 'Destination Wedding Clients',
    location: 'Ahmedabad',
    eventType: 'wedding',
    rating: 5,
    quote: "We had a destination wedding in Udaipur and honestly, I don't know how they managed to pull off something so magnificent. The decor, the food arrangements, guest transportation — absolutely flawless. 10/10, would recommend without hesitation.",
    date: '2025-02-20',
    platform: 'google',
    featured: true,
  },
  {
    id: 'test-004',
    name: 'Aisha Khan',
    role: 'Birthday Celebration Client',
    location: 'Bangalore',
    eventType: 'social',
    rating: 5,
    quote: "My 30th birthday was transformed into the most magical night. Anchor Shubham Khandelwal  understood my vision perfectly and delivered something even better than I imagined. The theme, the entertainment, the surprise moments — truly special.",
    date: '2024-09-12',
    platform: 'instagram',
    featured: false,
  },
  {
    id: 'test-005',
    name: 'Vikram Nair',
    role: 'Marketing Director, TechCorp India',
    location: 'Chennai',
    eventType: 'corporate',
    rating: 5,
    quote: "We launched our flagship product at an event organized by Anchor Shubham Khandelwal . The stage setup, LED walls, and media coordination were world-class. The event generated massive press coverage and we couldn't be happier.",
    date: '2024-12-05',
    platform: 'google',
    featured: true,
  },
  {
    id: 'test-006',
    name: 'Deepa & Rohan Verma',
    role: 'Wedding Clients',
    location: 'Jaipur',
    eventType: 'wedding',
    rating: 5,
    quote: "From the Mehendi to the Reception, every event in our wedding series was handled with absolute perfection. Anchor Shubham Khandelwal 's team is professional, creative, and genuinely invested in making your day perfect. Forever grateful.",
    date: '2025-01-28',
    platform: 'google',
    featured: false,
  },
  {
    id: 'test-007',
    name: 'Neha Gupta',
    role: 'Anniversary Celebration Client',
    location: 'Jaipur',
    eventType: 'social',
    rating: 5,
    quote: "Our 25th anniversary surprise party was orchestrated by Anchor Shubham Khandelwal  and my husband was completely blown away. The level of personalization and the secret coordination was incredible. Best evening of our lives!",
    date: '2025-03-14',
    platform: 'internal',
    featured: false,
  },
  {
    id: 'test-008',
    name: 'Suresh Kumar',
    role: 'VP Operations, Sunrise Group',
    location: 'Hyderabad',
    eventType: 'corporate',
    rating: 5,
    quote: "Anchor Shubham Khandelwal  managed our annual dealer meet with 800+ delegates. The logistics, the stage, the entertainment — everything was top-tier. Our dealers were incredibly impressed and it strengthened our brand perception significantly.",
    date: '2024-08-22',
    platform: 'google',
    featured: false,
  },
]

export const getFeaturedTestimonials = () => testimonials.filter((t) => t.featured)

export const getTestimonialsByCategory = (category: Testimonial['eventType']) =>
  testimonials.filter((t) => t.eventType === category)
