import type { Testimonial } from '@/types'

export const testimonials: Testimonial[] = [
  {
    id: 'test-001',
    name: 'Priya & Arjun',
    role: 'Wedding & Sangeet',
    location: 'Udaipur',
    eventType: 'wedding',
    rating: 5,
    quote: "Shubham didn't just host our sangeet — he ran it like a show. He pulled our shyest relatives onto the floor, sang live during the varmala, and kept 600 guests hooked till the last song. Every single person asked us for his number.",
    date: '2024-11-15',
    platform: 'google',
    featured: true,
  },
  {
    id: 'test-002',
    name: 'Rajesh Mehta',
    role: 'Head of Marketing',
    location: 'Jaipur',
    eventType: 'corporate',
    rating: 5,
    quote: "We've hired plenty of emcees for our annual awards. Shubham is on another level. He kept the agenda tight, handled a live glitch on stage without anyone noticing, and switched between Hindi and English effortlessly. Utterly professional.",
    date: '2024-10-08',
    platform: 'google',
    featured: true,
  },
  {
    id: 'test-003',
    name: 'Kavita & Sanjay',
    role: 'Reception Hosting',
    location: 'Jodhpur',
    eventType: 'wedding',
    rating: 5,
    quote: "Our reception could have been a long evening of announcements. Instead Shubham turned it into an experience — warm, funny, and perfectly paced. He read the room better than anyone I've ever seen with a mic.",
    date: '2025-02-20',
    platform: 'google',
    featured: true,
  },
  {
    id: 'test-004',
    name: 'Aisha Khan',
    role: 'Milestone Birthday',
    location: 'Jaipur',
    eventType: 'social',
    rating: 5,
    quote: "For my 30th I wanted energy, not a script being read out. Shubham brought games, banter and a live singing set that had everyone on their feet. He genuinely made the night about the people in the room.",
    date: '2024-09-12',
    platform: 'instagram',
    featured: false,
  },
  {
    id: 'test-005',
    name: 'Vikram Nair',
    role: 'Brand Launch — Emcee',
    location: 'Jaipur',
    eventType: 'corporate',
    rating: 5,
    quote: "Shubham hosted our product launch and set the perfect tone — polished, high-energy and completely in control. He made our leadership look great on stage and kept the audience engaged through every segment.",
    date: '2024-12-05',
    platform: 'google',
    featured: true,
  },
  {
    id: 'test-006',
    name: 'Deepa & Rohan',
    role: 'Full Wedding Series',
    location: 'Jaipur',
    eventType: 'wedding',
    rating: 5,
    quote: "From Haldi to Reception, Shubham anchored every function and each one felt fresh. He learned our family in-jokes, remembered names, and made both sides feel equally involved. Worth every rupee and more.",
    date: '2025-01-28',
    platform: 'google',
    featured: false,
  },
  {
    id: 'test-007',
    name: 'Neha Gupta',
    role: 'Anniversary Celebration',
    location: 'Ajmer',
    eventType: 'social',
    rating: 5,
    quote: "We planned a surprise 25th anniversary and Shubham held the whole evening together — the emotion, the timing, the music cues. My father-in-law, who never dances, was up front all night. That says everything.",
    date: '2025-03-14',
    platform: 'internal',
    featured: false,
  },
  {
    id: 'test-008',
    name: 'Suresh Kumar',
    role: 'Dealer Meet — Host',
    location: 'Kota',
    eventType: 'corporate',
    rating: 5,
    quote: "800 dealers, a two-hour agenda and a tough post-lunch slot — Shubham owned it. High energy, sharp transitions, and the crowd stayed with him the whole time. We've already booked him for next year.",
    date: '2024-08-22',
    platform: 'google',
    featured: false,
  },
]

export const getFeaturedTestimonials = () => testimonials.filter((t) => t.featured)

export const getTestimonialsByCategory = (category: Testimonial['eventType']) =>
  testimonials.filter((t) => t.eventType === category)
